USE [Cliente386_ERP]
GO

/****** Object:  View [dbo].[W_ESTOQUE_LIQUIDO_ATACADO]    Script Date: 07/08/2025 11:24:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER   VIEW [dbo].[W_ESTOQUE_LIQUIDO_ATACADO] AS

--============================================================================
	-- Calculo de estoque liquido subtraindo a necessidade da franquia
	-- Necessidade da Franquia é o saldo a entregar menos o que já está no estoque franquia - atacado
	-- 
--============================================================================

WITH ETQ_AT
AS
(SELECT * FROM [Cliente386_ERP].[dbo].[W_DRESS_ESTOQUE_PRODUTOS_DISPONIVEL] WHERE FILIAL = 'ATACADO' AND COLECAO IN (64, 65, 19)),

ETQ_FQ 
AS
(SELECT * FROM [Cliente386_ERP].[dbo].[W_DRESS_ESTOQUE_PRODUTOS_DISPONIVEL] WHERE FILIAL = 'FRANQUIA - ATACADO' AND COLECAO IN (64, 65)),

PD_FQ
AS
(SELECT S.ID_PRODUTO, SUM(VE1) AS VE1, SUM(VE2) AS VE2, SUM(VE3) AS VE3, SUM(VE4) AS VE4, SUM(VE5) AS VE5, SUM(VE6) AS VE6, SUM(VE7) AS VE7, SUM(VE8) AS VE8, SUM(QTDE_ENTREGAR) AS QTDE_ENTREGAR FROM [Cliente386_ERP].[dbo].[W_DRESS_WMS_ATACADO_SALDO_PEDIDO_ENTREGAR] AS S JOIN [Cliente386_ERP].[dbo].[PRODUTOS] AS P ON S.PRODUTO = P.PRODUTO 
    WHERE S.COLECAO IN (64, 65) AND APROVACAO = 'A' AND TIPO_CLIENTE = 'FRANQUIAS' AND FILIAL = 'FRANQUIA - ATACADO' AND TIPO_VENDA = 'VENDA' GROUP BY S.ID_PRODUTO)

SELECT A.*
	, (D1+D2+D3+D4+D5+D6+D7+D8) AS ESTOQUE_DISPONIVEL 
FROM 
	(
	SELECT EA.COD_FILIAL
		 , EA.FILIAL
		 , EA.PRODUTO
		 , EA.ID_PRODUTO
		 , EA.DESC_PRODUTO
		 , EA.COD_PRODUTO
		 , EA.DESC_COR_PRODUTO
		 , EA.COORDENADO
		 , EA.GRUPO_PRODUTO
		 , EA.SUBGRUPO_PRODUTO
		 , EA.LINHA
		 , EA.FABRICANTE
		 , EA.ESTILISTA
		 , EA.GRIFFE
		 , EA.COLECAO
		 , EA.DESC_COLECAO
		 , CASE WHEN (CASE WHEN EA.D1 <= 0 THEN 0 ELSE EA.D1 - (ISNULL(PF.VE1, 0) - ISNULL(EF.D1, 0)) END) < 0 THEN 0 ELSE (CASE WHEN EA.D1 <= 0 THEN 0 ELSE EA.D1 - (ISNULL(PF.VE1, 0) - ISNULL(EF.D1, 0)) END) END AS D1
		 --, CASE WHEN EA.D1 <= 0 THEN 0 ELSE EA.D1 - (ISNULL(PF.VE1, 0) - ISNULL(EF.D1, 0)) END AS D1
		 , CASE WHEN (CASE WHEN EA.D2 <= 0 THEN 0 ELSE EA.D2 - (ISNULL(PF.VE2, 0) - ISNULL(EF.D2, 0)) END) < 0 THEN 0 ELSE (CASE WHEN EA.D2 <= 0 THEN 0 ELSE EA.D2 - (ISNULL(PF.VE2, 0) - ISNULL(EF.D2, 0)) END) END AS D2
		 --, CASE WHEN EA.D2 <= 0 THEN 0 ELSE EA.D2 - (ISNULL(PF.VE2, 0) - ISNULL(EF.D2, 0)) END AS D2
		 , CASE WHEN (CASE WHEN EA.D3 <= 0 THEN 0 ELSE EA.D3 - (ISNULL(PF.VE3, 0) - ISNULL(EF.D3, 0)) END) < 0 THEN 0 ELSE (CASE WHEN EA.D3 <= 0 THEN 0 ELSE EA.D3 - (ISNULL(PF.VE3, 0) - ISNULL(EF.D3, 0)) END) END AS D3
		 --, CASE WHEN EA.D3 <= 0 THEN 0 ELSE EA.D3 - (ISNULL(PF.VE3, 0) - ISNULL(EF.D3, 0)) END AS D3
		 , CASE WHEN (CASE WHEN EA.D4 <= 0 THEN 0 ELSE EA.D4 - (ISNULL(PF.VE4, 0) - ISNULL(EF.D4, 0)) END) < 0 THEN 0 ELSE (CASE WHEN EA.D4 <= 0 THEN 0 ELSE EA.D4 - (ISNULL(PF.VE4, 0) - ISNULL(EF.D4, 0)) END) END AS D4
		 --, CASE WHEN EA.D4 <= 0 THEN 0 ELSE EA.D4 - (ISNULL(PF.VE4, 0) - ISNULL(EF.D4, 0)) END AS D4
		 , CASE WHEN (CASE WHEN EA.D5 <= 0 THEN 0 ELSE EA.D5 - (ISNULL(PF.VE5, 0) - ISNULL(EF.D5, 0)) END) < 0 THEN 0 ELSE (CASE WHEN EA.D5 <= 0 THEN 0 ELSE EA.D5 - (ISNULL(PF.VE5, 0) - ISNULL(EF.D5, 0)) END) END AS D5
		 --, CASE WHEN EA.D5 <= 0 THEN 0 ELSE EA.D5 - (ISNULL(PF.VE5, 0) - ISNULL(EF.D5, 0)) END AS D5
		 , CASE WHEN (CASE WHEN EA.D6 <= 0 THEN 0 ELSE EA.D6 - (ISNULL(PF.VE6, 0) - ISNULL(EF.D6, 0)) END) < 0 THEN 0 ELSE (CASE WHEN EA.D6 <= 0 THEN 0 ELSE EA.D6 - (ISNULL(PF.VE6, 0) - ISNULL(EF.D6, 0)) END) END AS D6
		 --, CASE WHEN EA.D6 <= 0 THEN 0 ELSE EA.D6 - (ISNULL(PF.VE6, 0) - ISNULL(EF.D6, 0)) END AS D6
		 , CASE WHEN (CASE WHEN EA.D7 <= 0 THEN 0 ELSE EA.D7 - (ISNULL(PF.VE7, 0) - ISNULL(EF.D7, 0)) END) < 0 THEN 0 ELSE (CASE WHEN EA.D7 <= 0 THEN 0 ELSE EA.D7 - (ISNULL(PF.VE7, 0) - ISNULL(EF.D7, 0)) END) END AS D7
		 --, CASE WHEN EA.D7 <= 0 THEN 0 ELSE EA.D7 - (ISNULL(PF.VE7, 0) - ISNULL(EF.D7, 0)) END AS D7
		 , CASE WHEN (CASE WHEN EA.D8 <= 0 THEN 0 ELSE EA.D8 - (ISNULL(PF.VE8, 0) - ISNULL(EF.D8, 0)) END) < 0 THEN 0 ELSE (CASE WHEN EA.D8 <= 0 THEN 0 ELSE EA.D8 - (ISNULL(PF.VE8, 0) - ISNULL(EF.D8, 0)) END) END AS D8
		 --, CASE WHEN EA.D8 <= 0 THEN 0 ELSE EA.D8 - (ISNULL(PF.VE8, 0) - ISNULL(EF.D8, 0)) END AS D8
	FROM ETQ_AT AS EA
		LEFT JOIN ETQ_FQ AS EF ON EA.ID_PRODUTO = EF.ID_PRODUTO
		LEFT JOIN PD_FQ AS PF ON EA.ID_PRODUTO = PF.ID_PRODUTO

	) AS A
GO


