--EXEC [dbo].[sp_distribuicao_atacado]


SELECT  
	   A.PEDIDO
	 , A.CLIENTE
	 , A.REPRESENTANTE
	 , A.TRANSPORTADORA
	 , A.TIPO_BLOQUEIO
	 , A.TOTAL_ORIGINAL
	 , A.VALOR_A_RESERVAR
	 , CAST(V.[VALOR_ENTREGUE] AS NUMERIC(10,2)) AS VALOR_ENTREGUE
	 , A.MINIMO_FAT
	 , A.PRODUTO
	 , A.COR_PRODUTO
	 , A.ID_PRODUTO
	 , A.DESC_PRODUTO
	 , A.ITEM_PEDIDO
	 , A.ENTREGA
	 , A.DESC_COR
	 , A.COORDENADO
	 , A.COORD_PD
	 , A.COORD_ATD
	 , A.FATURADO_NO_COORD
	 , A.[(%) COORD ATD]
	 , A.[(%) QTDE_ATENDIDO]
	 , A.[(%) GRADE_ATD]
	 , A.FATURADO_NO_PROD
	 , A.[PRIORIDADE]
     , A.[NEC_P1]
     , A.[NEC_P2]
     , A.[NEC_P3]
     , A.[NEC_P4]
     , A.[NEC_P5]
     , A.[NEC_P6]
     , A.[TOTAL_NECESSIDADE]
     , A.QTDE_ORIGINAL
     , A.[ALOC_P1]
     , A.[ALOC_P2]
     , A.[ALOC_P3]
     , A.[ALOC_P4]
     , A.[ALOC_P5]
     , A.[ALOC_P6]
     , A.[TOTAL_ALOCADO]
     , A.[PRECO]
     , A.[TOTAL_ALOCADO] * A.[PRECO] AS VALOR_ALOCADO
     , A.[RESTANTE_P1]
     , A.[RESTANTE_P2]
     , A.[RESTANTE_P3]
     , A.[RESTANTE_P4]
     , A.[RESTANTE_P5]
     , A.[RESTANTE_P6]
     , A.[TOTAL_NAO_ATENDIDO]
	 , A.[PROGRAMACOES]
	 , A.[PREVISAO_ENTREGA]
	 , A.[QTDE_RECEBER]
	 , A.[ORIGEM]
	 , A.[DATA_ATUALIZACAO]
	 , V.PEDIDO_CLIENTE AS PEDIDO_CLIENTE
FROM(
	SELECT
			TRIM(R.[PEDIDO]) AS PEDIDO
		  , TRIM(R.[CLIENTE]) AS CLIENTE
		  , CASE WHEN R.CLIENTE = 'ICOMM 2' THEN 'SITE_MODANET'
				 WHEN R.CLIENTE = 'MODANET' THEN 'SITE_MODANET'
				 WHEN R.CLIENTE = 'MM DAFITI FL 5 EXTREMA' THEN 'SITE_DAFITI'
				 ELSE CR.REPRESENTANTE
			END REPRESENTANTE
		  , C.TRANSPORTADORA
		  , C.TIPO_BLOQUEIO
		  , R.TOTAL_ORIGINAL
		  , SUM(R.[TOTAL_ALOCADO] * R.[PRECO]) OVER(PARTITION BY(R.[CLIENTE])) AS VALOR_A_RESERVAR
		  --, CAST(V.[VALOR_ENTREGUE] AS NUMERIC(10,2)) AS VALOR_ENTREGUE 
		  , CASE WHEN SUM(R.[TOTAL_ALOCADO] * R.[PRECO]) OVER(PARTITION BY(R.[CLIENTE])) >= 1500.00 THEN 'SIM' ELSE 'NÃO' END AS MINIMO_FAT
		  , R.PRODUTO
		  , R.[COR_PRODUTO]
		  , R.[ID_PRODUTO]
		  , P.DESC_PRODUTO
		  , VND.COLECAO
		  , R.ITEM_PEDIDO
		  , CONVERT(VARCHAR(8), R.ENTREGA, 112) AS ENTREGA
		  , PC.DESC_COR_PRODUTO AS DESC_COR
		  , ISNULL(R.[COORDENADO], '') AS COORDENADO
		  , CASE WHEN R.[COORDENADO] IS NULL OR R.[COORDENADO] = ''  THEN 1 ELSE COUNT(*) OVER (PARTITION BY R.[CLIENTE], R.[COORDENADO], R.[COR_PRODUTO]) END AS COORD_PD
		  , CASE WHEN R.[COORDENADO] IS NULL OR R.[COORDENADO] = '' THEN CASE WHEN R.[TOTAL_ALOCADO] > 0 THEN 1 ELSE 0 END ELSE SUM(CASE WHEN R.[TOTAL_ALOCADO] > 0 THEN 1 ELSE 0 END) OVER (PARTITION BY R.[CLIENTE], R.[COORDENADO], R.[COR_PRODUTO]) END AS COORD_ATD
		  --================================================================
		  , CASE WHEN SUM(R.[TOTAL_NECESSIDADE]) OVER (PARTITION BY R.[CLIENTE], R.[COORDENADO], R.[COR_PRODUTO]) < SUM(VND.QTDE_ORIGINAL) OVER (PARTITION BY R.[CLIENTE], R.[COORDENADO], R.[COR_PRODUTO]) THEN 'Sim' ELSE 'Não' END AS [FATURADO_NO_COORD]
		  --================================================================
		  --, R.[TOTAL_ALOCADO] / R.[TOTAL_NECESSIDADE] AS [(%) QTDE_ATENDIDO]  
		  --, (CASE WHEN R.[COORDENADO] IS NULL OR R.[COORDENADO] = '' THEN CASE WHEN R.[TOTAL_ALOCADO] > 0 THEN 1 ELSE 0 END ELSE SUM(CASE WHEN R.[TOTAL_ALOCADO] > 0 THEN 1 ELSE 0 END) OVER (PARTITION BY R.[PEDIDO], R.[COORDENADO], R.[COR_PRODUTO]) END) / (CASE WHEN R.[COORDENADO] IS NULL OR R.[COORDENADO] = '' THEN 1 ELSE COUNT(*) OVER (PARTITION BY R.[PEDIDO], R.[COORDENADO], R.[COR_PRODUTO]) END) AS [(%) COORD ATD]
		  --, CAST((CASE WHEN R.[COORDENADO] IS NULL OR R.[COORDENADO] = '' THEN CASE WHEN R.[TOTAL_ALOCADO] > 0 THEN 1 ELSE 0 END ELSE SUM(CASE WHEN R.[TOTAL_ALOCADO] > 0 THEN 1 ELSE 0 END) OVER (PARTITION BY R.[CLIENTE], R.[COORDENADO], R.[COR_PRODUTO]) END) AS REAL) / (CASE WHEN R.[COORDENADO] IS NULL OR R.[COORDENADO] = '' THEN 1 ELSE COUNT(*) OVER (PARTITION BY R.[CLIENTE], R.[COORDENADO], R.[COR_PRODUTO]) END) AS [(%) COORD ATD]
		  , CAST((CASE WHEN R.[COORDENADO] IS NULL OR R.[COORDENADO] = '' THEN CASE WHEN R.[TOTAL_ALOCADO] > 0 THEN 1 ELSE 0 END ELSE SUM(CASE WHEN R.[TOTAL_ALOCADO] > 0 THEN 1 ELSE 0 END) OVER (PARTITION BY R.[CLIENTE], R.[COORDENADO], R.[COR_PRODUTO]) END) AS REAL) / (CASE WHEN R.[COORDENADO] IS NULL OR R.[COORDENADO] = '' THEN 1 ELSE COUNT(*) OVER (PARTITION BY R.[CLIENTE], R.[COORDENADO], R.[COR_PRODUTO]) END) AS [(%) COORD ATD]  
		  /*
		  , CASE WHEN((CASE WHEN NEC_P1 > 0 THEN 1 ELSE 0 END) + (CASE WHEN NEC_P2 > 0 THEN 1 ELSE 0 END) + (CASE WHEN NEC_P3 > 0 THEN 1 ELSE 0 END) + (CASE WHEN NEC_P4 > 0 THEN 1 ELSE 0 END) + (CASE WHEN NEC_P5 > 0 THEN 1 ELSE 0 END) + (CASE WHEN NEC_P6 > 0 THEN 1 ELSE 0 END)) = 0 THEN 0
				 ELSE CAST(((CASE WHEN ALOC_P1 > 0 THEN 1 ELSE 0 END) + (CASE WHEN ALOC_P2 > 0 THEN 1 ELSE 0 END) + (CASE WHEN ALOC_P3 > 0 THEN 1 ELSE 0 END) + (CASE WHEN ALOC_P4 > 0 THEN 1 ELSE 0 END) + (CASE WHEN ALOC_P5 > 0 THEN 1 ELSE 0 END) + (CASE WHEN ALOC_P6 > 0 THEN 1 ELSE 0 END)) AS REAL) / ((CASE WHEN NEC_P1 > 0 THEN 1 ELSE 0 END) + (CASE WHEN NEC_P2 > 0 THEN 1 ELSE 0 END) + (CASE WHEN NEC_P3 > 0 THEN 1 ELSE 0 END) + (CASE WHEN NEC_P4 > 0 THEN 1 ELSE 0 END) + (CASE WHEN NEC_P5 > 0 THEN 1 ELSE 0 END) + (CASE WHEN NEC_P6 > 0 THEN 1 ELSE 0 END)) END AS [(%) QTDE_ATENDIDO]
		  */
		  , CASE WHEN (CAST(ALOC_P1 AS NUMERIC(10,2))+CAST(ALOC_P2 AS NUMERIC(10,2))+CAST(ALOC_P3 AS NUMERIC(10,2))+CAST(ALOC_P4 AS NUMERIC(10,2))+CAST(ALOC_P5 AS NUMERIC(10,2))+CAST(ALOC_P6 AS NUMERIC(10,2))) = 0 THEN 0 
				 ELSE (CAST(ALOC_P1 AS NUMERIC(10,2))+CAST(ALOC_P2 AS NUMERIC(10,2))+CAST(ALOC_P3 AS NUMERIC(10,2))+CAST(ALOC_P4 AS NUMERIC(10,2))+CAST(ALOC_P5 AS NUMERIC(10,2))+CAST(ALOC_P6 AS NUMERIC(10,2))) / (CAST(NEC_P1 AS NUMERIC(10,2))+CAST(NEC_P2 AS NUMERIC(10,2))+CAST(NEC_P3 AS NUMERIC(10,2))+CAST(NEC_P4 AS NUMERIC(10,2))+CAST(NEC_P5 AS NUMERIC(10,2))+CAST(NEC_P6 AS NUMERIC(10,2))) END AS [(%) QTDE_ATENDIDO]
		  , CASE WHEN((CASE WHEN NEC_P1 > 0 THEN 1 ELSE 0 END) + (CASE WHEN NEC_P2 > 0 THEN 1 ELSE 0 END) + (CASE WHEN NEC_P3 > 0 THEN 1 ELSE 0 END) + (CASE WHEN NEC_P4 > 0 THEN 1 ELSE 0 END) + (CASE WHEN NEC_P5 > 0 THEN 1 ELSE 0 END) + (CASE WHEN NEC_P6 > 0 THEN 1 ELSE 0 END)) = 0 THEN 0
				 ELSE CAST(((CASE WHEN ALOC_P1 > 0 THEN 1 ELSE 0 END) + (CASE WHEN ALOC_P2 > 0 THEN 1 ELSE 0 END) + (CASE WHEN ALOC_P3 > 0 THEN 1 ELSE 0 END) + (CASE WHEN ALOC_P4 > 0 THEN 1 ELSE 0 END) + (CASE WHEN ALOC_P5 > 0 THEN 1 ELSE 0 END) + (CASE WHEN ALOC_P6 > 0 THEN 1 ELSE 0 END)) AS REAL)/((CASE WHEN NEC_P1 > 0 THEN 1 ELSE 0 END) + (CASE WHEN NEC_P2 > 0 THEN 1 ELSE 0 END) + (CASE WHEN NEC_P3 > 0 THEN 1 ELSE 0 END) +  (CASE WHEN NEC_P4 > 0 THEN 1 ELSE 0 END) + (CASE WHEN NEC_P5 > 0 THEN 1 ELSE 0 END) + (CASE WHEN NEC_P6 > 0 THEN 1 ELSE 0 END)) END AS [(%) GRADE_ATD]
		  --================================================================
		  , CASE WHEN SUM(R.[TOTAL_NECESSIDADE]) OVER (PARTITION BY R.[CLIENTE], R.[COORDENADO], R.[PRODUTO] ,R.[COR_PRODUTO]) < VND.QTDE_ORIGINAL  THEN 'Sim' ELSE 'Não' END AS [FATURADO_NO_PROD]
		  --================================================================
		  , R.[PRIORIDADE]
		  , R.[NEC_P1]
		  , R.[NEC_P2]
		  , R.[NEC_P3]
		  , R.[NEC_P4]
		  , R.[NEC_P5]
		  , R.[NEC_P6]
		  , R.[TOTAL_NECESSIDADE]
		  , VND.QTDE_ORIGINAL
		  , R.[ALOC_P1]
		  , R.[ALOC_P2]
		  , R.[ALOC_P3]
		  , R.[ALOC_P4]
		  , R.[ALOC_P5]
		  , R.[ALOC_P6]
		  , R.[TOTAL_ALOCADO]
		  , R.[PRECO]
		  , R.[TOTAL_ALOCADO] * R.[PRECO] AS VALOR_ALOCADO
		  , R.[RESTANTE_P1]
		  , R.[RESTANTE_P2]
		  , R.[RESTANTE_P3]
		  , R.[RESTANTE_P4]
		  , R.[RESTANTE_P5]
		  , R.[RESTANTE_P6]
		  , R.[TOTAL_NAO_ATENDIDO]
		  , COALESCE((CASE WHEN PRG.QTDE_EM_PRODUCAO = 0 THEN NULL ELSE PRG.PROGRAMACOES END), PE.PROGRAMACAO, PG.PROGRAMACAO, '') AS PROGRAMACOES
		  , COALESCE((CASE WHEN PRG.QTDE_EM_PRODUCAO = 0 THEN NULL ELSE PRG.PREVISAO_ENTREGA END), PE.DT_ENTREGA, 'SEM PREVISÃO') AS PREVISAO_ENTREGA
		  --, CASE WHEN PRG.QTDE_EM_PRODUCAO = 0 OR PRG.QTDE_EM_PRODUCAO IS NULL THEN PG.TOT_PROG ELSE PRG.QTDE_EM_PRODUCAO END QTDE_RECEBER_X
		  , COALESCE((CASE WHEN PRG.QTDE_EM_PRODUCAO = 0 THEN NULL ELSE PRG.QTDE_EM_PRODUCAO END), PE.QTDE_ENTREGAR, PG.TOT_PROG) AS QTDE_RECEBER
		  , COALESCE(PRG.TABELA, PE.TABELA, PG.TABELA, '') AS ORIGEM
		  , R.[DATA_ATUALIZACAO]
		  --, V.PEDIDO_CLIENTE AS PEDIDO_CLIENTE

	FROM [dbo].[RESULTADO_DISTRIBUICAO_ATACADO] AS R WITH (NOLOCK)
		JOIN (SELECT CONCAT(RTRIM(PRODUTO), '-', RTRIM(COR_PRODUTO)) COLLATE SQL_Latin1_General_CP1_CI_AS AS ID_PRODUTO, PRODUTO, DESC_COR_PRODUTO FROM [Cliente386_ERP].[dbo].[PRODUTO_CORES] ) AS PC ON R.ID_PRODUTO = PC.ID_PRODUTO 
		JOIN (SELECT RTRIM(PRODUTO) COLLATE SQL_Latin1_General_CP1_CI_AS AS PRODUTO, UPPER(RTRIM(DESC_PRODUTO)) AS DESC_PRODUTO FROM [Cliente386_ERP].[dbo].[PRODUTOS]) AS P ON LEFT(R.ID_PRODUTO, 10) = P.PRODUTO
		JOIN (SELECT RTRIM(CLIENTE_ATACADO) COLLATE SQL_Latin1_General_CP1_CI_AS AS CLIENTE_ATACADO, RTRIM(COD_CLIENTE) AS COD_CLIENTE, TRIM(TRANSPORTADORA) AS TRANSPORTADORA, RTRIM(TIPO_BLOQUEIO) AS TIPO_BLOQUEIO FROM [Cliente386_ERP].[dbo].[CLIENTES_ATACADO]) AS C ON R.CLIENTE = C.CLIENTE_ATACADO
		JOIN (SELECT CLIENTE_ATACADO, TRIM(REPRESENTANTE) AS REPRESENTANTE FROM CLIENTE_REPRE) AS CR ON C.CLIENTE_ATACADO = CR.CLIENTE_ATACADO
		LEFT JOIN (
					SELECT A.PRODUTO, A.COR_PRODUTO, P.COLECAO, STRING_AGG(TRIM(POC.PROGRAMACAO), ', ') PROGRAMACOES
					  --, STRING_AGG(COALESCE(TRY_CONVERT(DATE, [DT_RETRABALHO], 103), TRY_CONVERT(DATE, [DT_CONFIRMADA], 103), TRY_CONVERT(DATE, [DT_NEGOCIADA], 103)), ', ') AS PREVSAO_ENTREGA
						, COALESCE(STRING_AGG(COALESCE([DT_RETRABALHO], [DT_CONFIRMADA], [DT_NEGOCIADA]), ', '), 'SEM PREVISÃO') AS PREVISAO_ENTREGA
						, STRING_AGG(TRIM(A.[ORDEM_PRODUCAO]), ', ') AS ORDENS_PRODUCAO
						--, A.[ORDEM_PRODUCAO]
						--, SUM(QTDE_EM_PRODUCAO) AS QTDE_EM_PRODUCAO
						, SUM(QTDE_P) AS QTDE_EM_PRODUCAO
						, 'OP' AS TABELA
					FROM [Cliente386_ERP].[dbo].[PRODUCAO_ORDEM_COR] A
						LEFT JOIN [Cliente386_ERP].[dbo].[W_FACCAO_AGENDAMENTO] AS PO WITH (NOLOCK) ON A.ORDEM_PRODUCAO = PO.ORDEM_PRODUCAO
						LEFT JOIN [Cliente386_ERP].[dbo].[PRODUCAO_ORDEM] AS POC WITH (NOLOCK) ON A.ORDEM_PRODUCAO = POC.ORDEM_PRODUCAO
						--LEFT JOIN W_PROGRAMACAO_CONSOLIDADA AS PC ON A.PRODUTO = PC.produto AND A.COR_PRODUTO = PC.COR_PRODUTO
						LEFT JOIN PRODUTOS AS P ON A.PRODUTO = P.PRODUTO
					WHERE POC.PROGRAMACAO LIKE '%ATACADO%' AND COLECAO IN (64, 65) /*AND A.PRODUTO = '02.08.3174'*/ GROUP BY A.PRODUTO, A.COR_PRODUTO, P.COLECAO--, A.[ORDEM_PRODUCAO]
				  ) AS PRG ON TRIM(R.PRODUTO) = TRIM(PRG.PRODUTO) AND R.COR_PRODUTO = PRG.COR_PRODUTO
		LEFT JOIN (
					SELECT 
						  TRIM(CP.PRODUTO) AS PRODUTO
						, TRIM(CP.COR_PRODUTO) AS COR_PRODUTO
						, CONCAT(TRIM(CP.PRODUTO), '.', TRIM(CP.COR_PRODUTO)) AS ID_PRODUTO
						, SUM(CP.QTDE_ENTREGAR) AS QTDE_ENTREGAR
						, STRING_AGG(CONVERT(VARCHAR, CAST(ENTREGA AS DATE), 103), ', ') AS DT_ENTREGA
						, STRING_AGG(C.PROGRAMACAO, ', ') AS PROGRAMACAO
						, 'PE' AS TABELA
					FROM [dbo].[COMPRAS_PRODUTO] AS CP WITH (NOLOCK)
						JOIN [dbo].[COMPRAS] AS C ON CP.PEDIDO = C.PEDIDO
						JOIN PRODUTOS AS P WITH (NOLOCK) ON TRIM(CP.PRODUTO) = TRIM(P.PRODUTO)
					WHERE 1=1
					  AND COLECAO IN (64, 65) AND C.PROGRAMACAO LIKE '%ATACADO%'
					GROUP BY TRIM(CP.PRODUTO), TRIM(CP.COR_PRODUTO), CONCAT(TRIM(CP.PRODUTO), '.', TRIM(CP.COR_PRODUTO))
					) AS PE ON LEFT(R.ID_PRODUTO, 10) = PE.PRODUTO AND R.COR_PRODUTO = PE.COR_PRODUTO

		LEFT JOIN (
					SELECT PRODUTO, COR_PRODUTO , ID_PRODUTO , SUM(TOT_PROG) AS TOT_PROG , STRING_AGG(PROGRAMACAO, ', ') AS PROGRAMACAO , 'PG' AS TABELA
					FROM(SELECT TRIM(PROGRAMACAO) AS PROGRAMACAO , TRIM(PG.PRODUTO) AS PRODUTO, TRIM(COR_PRODUTO) AS COR_PRODUTO, CONCAT(TRIM(PG.PRODUTO), '.', TRIM(COR_PRODUTO)) AS ID_PRODUTO, SUM(S1 + S2 + S3 + S4 + S5 + S6) AS TOT_PROG
							FROM [dbo].[WMRP_PROGRAMACAO_PRODUTO_GRADE] AS PG WITH (NOLOCK) JOIN PRODUTOS AS P ON PG.PRODUTO = P.PRODUTO WHERE PROGRAMACAO LIKE '%ATACADO%' AND COLECAO IN (64, 65)
							GROUP BY PROGRAMACAO, PG.PRODUTO, COR_PRODUTO, CONCAT(TRIM(PG.PRODUTO), '.', TRIM(COR_PRODUTO))) AS A 
					GROUP BY PRODUTO, COR_PRODUTO, ID_PRODUTO
				
				   ) AS PG ON LEFT(R.ID_PRODUTO, 10) = PG.PRODUTO AND R.COR_PRODUTO = PG.COR_PRODUTO

		--LEFT JOIN (SELECT CLIENTE_ATACADO, STRING_AGG(TRIM(PEDIDO_CLIENTE), ',') AS PEDIDO_CLIENTE, COLECAO, SUM(TOT_VALOR_ENTREGUE) AS VALOR_ENTREGUE FROM VENDAS WHERE 1=1 AND TIPO = 'VENDA' AND FILIAL = 'ATACADO' AND COLECAO IN (64, 65) GROUP BY CLIENTE_ATACADO, COLECAO) AS V ON R.CLIENTE = V.CLIENTE_ATACADO
		LEFT JOIN (SELECT CLIENTE_ATACADO, COLECAO, PRODUTO, COR_PRODUTO, SUM(VP.QTDE_ORIGINAL) AS QTDE_ORIGINAL FROM VENDAS_PRODUTO AS VP JOIN VENDAS AS V ON VP.PEDIDO = V.PEDIDO WHERE 1=1 AND TIPO = 'VENDA' AND FILIAL = 'ATACADO' AND COLECAO IN (64, 65) AND QTDE_ENTREGAR > 0 GROUP BY CLIENTE_ATACADO, COLECAO, PRODUTO, COR_PRODUTO) AS VND ON R.CLIENTE = VND.CLIENTE_ATACADO AND R.ID_PRODUTO = CONCAT(TRIM(VND.PRODUTO), '-', TRIM(VND.COR_PRODUTO))

	WHERE 1=1 
	
		--AND TOTAL_NECESSIDADE > 0
		--AND R.ID_PRODUTO = '02.08.3187-198'
		--AND PEDIDO IN ('2398791') AND COORDENADO = 'CDM64-EST ESSÊNCIA' --AND R.COR_PRODUTO = '2352'
) AS A
LEFT JOIN (SELECT CLIENTE_ATACADO, STRING_AGG(TRIM(PEDIDO_CLIENTE), ',') AS PEDIDO_CLIENTE, COLECAO, SUM(TOT_VALOR_ENTREGUE) AS VALOR_ENTREGUE FROM VENDAS WHERE 1=1 AND TIPO = 'VENDA' AND FILIAL = 'ATACADO' AND COLECAO IN (64, 65) GROUP BY CLIENTE_ATACADO, COLECAO) AS V ON A.CLIENTE = V.CLIENTE_ATACADO AND A.COLECAO = V.COLECAO
WHERE 1=1 
  AND TOTAL_NECESSIDADE > 0 
  --and PEDIDO = '2398791'
  --AND COLECAO = 64
  --AND PEDIDO = '2410403'
  --AND COORDENADO = 'CDTP64-FOLHAR'

